apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: web          # This tells the service to find the "nametag" we put on the deployment
  ports:
    - protocol: TCP
      port: 80        # The port people use to access the service
      targetPort: 80  # The port the Nginx container is listening on
  type: NodePort      # This lets you access it on your laptop's IP